version: "3"
services:
  database:
    image: mariadb:11.0-rc-jammy
    restart: always
    env_file:
      - ./database/maria-env
    environment:
      TZ: Asia/Seoul
    volumes: # host:container
      - ./database/maria-init.sql:/docker-entrypoint-initdb.d/maria-init.sql
    ports:
      - "3306:3306"
  
  users:
    build: ./users
    # image: python:3.10
    restart: always
    environment:
      DB_URL: database
      DB_NAME: exampledb
      DB_PORT: 3306
      DB_USERNAME: testusr
      DB_PASSWORD: 1234
    ports:
      - "5556:5556"
    depends_on:
      - database

