CREATE DATABASE IF NOT EXISTS exampledb;

CREATE TABLE User (
	   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	   updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	   username VARCHAR(20),
	   password VARCHAR(128),
	   email VARCHAR(50) DEFAULT '',

	   userType INT NOT NULL DEFAULT 0,
	   isAdmin BOOLEAN NOT NULL DEFAULT 0,
	   noShowCount INT NOT NULL DEFAULT 0,
	   isBanned INT NOT NULL DEFAULT 0	   
) DEFAULT CHARSET=utf8;
